### PR TITLE
added maintainer

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by doudou** [comment]
If you're the maintainer, I would suggest that you agree and apply your PR ;-)

**Comment by goldhoorn** [comment]
Ack for me :)

**Comment by planthaber** [comment]
I agree that I am the maintainer

**Comment by leifole** [comment]
Don't know why I am associated with this package, can't remember having
contributed. Long story short: I'm out ;-)

Best,
Leif

Am 01.04.2015 um 16:38 schrieb Steffen Planthaber:

**Comment by doudou** [comment]
@leifole: if by "being associated" you mean "getting github notifications", that's because you are in the devel team for github's rock-drivers organization. Just disable notifications for this package.

**Comment by doudou** [comment]
@planthaber: missed the important bit ... you were not in the organization ...

**Pull request merged**
